### ISSUE TITLE
ImportError:No moudle named 'util'

### ISSUE THREAD

**Issue by yangyingni** [cydiachen/FSRNET_pytorch#16]
运行代码的时候一直出现这个问题，请问如何解决呢

**Comment by JauB1981** [comment]
On which file do you have this error ? train.py or other file ?

**Comment by ghost** [comment]
请问一下你解决这个问题了么？

**Comment by JauB1981** [comment]
> 请问一下你解决这个问题了么？

What's exactly your problem so I can help you ?

**Comment by ghost** [comment]
> > 请问一下你解决这个问题了么？
> 
> What's exactly your problem so I can help you ?

just the title problem "ImportError:No moudle named 'util'“

**Comment by ghost** [comment]
> > 请问一下你解决这个问题了么？
> 
> What's exactly your problem so I can help you ?

the file "losses.py"

**Comment by JauB1981** [comment]
> > > 请问一下你解决这个问题了么？
> > 
> > 
> > What's exactly your problem so I can help you ?
> 
> the file "losses.py"

There is no need to use losses.py !

**Comment by TeiZouen** [comment]
@cydiachen 　Please let me know how to resolve this.
I'm having the same problem.
python train.py 
Traceback (most recent call last):
  File "train.py", line 27, in <module>
    from models import losses
  File "/home/teizouen/Documents/FSRNET_pytorch/models/losses.py", line 8, in <module>
    import util.util as util
ModuleNotFoundError: No module named 'util'

**Comment by TeiZouen** [comment]
@yangyingni 
你解决了这个问题吗？如果解决了，请告诉解决办法，谢谢
